name = "MolecularConformation"
uuid = "727cb4de-92cd-11e9-02b2-7deda15fe764"
authors = ["evcastelani <emersonvitor@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
