name = "MolecularConformation"
uuid = "727cb4de-92cd-11e9-02b2-7deda15fe764"
authors = ["evcastelani <emersonvitor@gmail.com>", "Guilherme Philippi", "Felipe Fidalgo"]
version = "0.1.3"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

